### ISSUE TITLE
the game stuck on main menu right after installing cement

### ISSUE THREAD

**Issue by abdogm** [HueSamai/CementSource#15]
hello
(my apologies for my bad nglish)

this happen when there was no mods loaded
after installing cement by following the steps from discord, no matter what i do i get stuck at this screen
![image](https://github.com/HueSamai/CementSource/assets/72724405/f39302b8-8102-467f-8201-2d56b4dd10de)
any idea how to fix it

**Comment by HueSamai** [comment]
You are using an old version of the game, or a cracked version. Try running it on the latest version of Gang Beasts.
