### ISSUE TITLE
How do I download it 

### ISSUE THREAD

**Issue by ItsmcFox** [HueSamai/CementSource#21]
It doesn’t seem like there is a way to download

**Comment by TheUltimateNuke** [comment]
Cement is undergoing a large rewrite at the moment and is currently broken for the latest version of Gang Beasts. 
If you own the game on Steam and you have some technical knowledge, you can Google around for how to downgrade Steam games in the meantime. The version you're looking to downgrade to is v1.21

**Comment by ItsmcFox** [comment]
Does assembly-csharp.dll have to do anything with this?

**Comment by HueSamai** [comment]
Well, sort of. The game changed the programming language it runs in. So it doesn't have a Assembly-CSharp.dll file anymore. All of it is compiled to assembly. If you want mods and to run cement, then join the discord by going to the website, and then in the announcements channel, there is a link to download the cement installer. Just know that in order for the Cement installer to work and Cement to run, you need to downgrade your game first. There is also a guide in announcements in the discord. I hope this helps.

**Comment by ItsmcFox** [comment]
What will the cement installer file type be?

**Comment by HueSamai** [comment]
It is an executable.

**Comment by ItsmcFox** [comment]
Will it work on Xbox?

**Comment by HueSamai** [comment]
No. Unfortunately, it only works on downgraded Gang Beasts, and you can only downgrade on steam, at least that I'm aware of.

**Comment by ItsmcFox** [comment]
No like the new one

**Comment by HueSamai** [comment]
Oh, yeah the new one should.

**Comment by ItsmcFox** [comment]
So it should work on Xbox?

**Comment by HueSamai** [comment]
Yeah. I'm not involved with the development really. You should talk to Nuke, but I'm sure it will. It's still under development tho. It's not released yet.

**Comment by ItsmcFox** [comment]
What coding language was gang beasts in before and now? The game seems the exact same

**Comment by HueSamai** [comment]
No, so it's written in the same programming language, but it's compiled to different ones. So the game's code hasn't changed but the code it runs on has. It originally ran on C#'s IL code, but now it runs on native assembly.

**Comment by ItsmcFox** [comment]
Oh do you know about when it will be fixed?

**Comment by HueSamai** [comment]
Cement? I don't have an idea. I'm not working on it. It's only Nuke working on it now.

**Comment by ItsmcFox** [comment]
@TheUltimateNuke When do you think cement will be fixed?

**Comment by TheUltimateNuke** [comment]
We get asked this question commonly on the Discord. There's no way of knowing when it'll be fixed. It will be released when bugs are minimal and the rewrite's main vision (features, utilities for modders, etc) is fully implemented, and there is no date we can set for that kind of thing when we do it in our free time and for fun.

**Comment by ItsmcFox** [comment]
Ok
